# Generated by Django 2.2.17 on 2021-02-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placas',
            name='no_Cedula',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
