# Generated by Django 2.2.17 on 2021-02-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_placas_no_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placas',
            name='chasis',
            field=models.CharField(max_length=20),
        ),
    ]
